---
#tcp:
#  active: true
#  port: 8080
#udp:
#  active: true
#  port: 52167
#  host: 127.0.0.1
#mappings: []
statful:
  flushInterval: 5000
  flushSize: 10
  dryRun: false
  host: localhost
  port: 2013
  app: statsdexporter
  namespace: statsdexporter
  environment: local
